# Generated by Django 2.1.9 on 2019-07-02 03:09

from django.db import migrations, models
import quotes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='author')),
                ('quote', models.TextField(verbose_name='quote')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=quotes.models.upload_to, verbose_name='picture')),
            ],
            options={
                'verbose_name': 'quote',
                'verbose_name_plural': 'quote',
            },
        ),
    ]
